name: Dynamic Scheduler
description: A dynamic scheduler action for managing workflow steps
inputs:
  workflow_file:
    description: Optional path to the workflow file
    required: false
  debug:
    description: Enable debug mode
    required: false
    default: 'true'
outputs:
  jobNames:
    description: List of job names from the API response
  workflowPath:
    description: Path to the workflow file
  content:
    description: Workflow content (only when debug is true)
runs:
  using: node20
  main: dist/index.js 