name: Dynamic Scheduler
description: A dynamic scheduler action for managing workflow steps
inputs:
  workflow_file:
    description: Optional path to the workflow file
    required: false
  debug:
    description: Enable debug mode
    required: false
    default: 'true'
  continue_on_error:
    description: Continue workflow execution if this step fails
    required: false
    default: 'false'
outputs:
  jobNames:
    description: List of job names from the API response
  workflowPath:
    description: Path to the workflow file
  content:
    description: Workflow content (only when debug is true)
  skip:
    description: JSON object containing skip flags for each step
runs:
  using: node20
  main: dist/index.js
