name: Bazel BuildBuddy Tests

permissions: read-all

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request: {}

jobs:
  bazel_buildbuddy_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Run tests
        id: run_tests
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          bazel test //bazel/python/tests:stock_data_test \
            --config=buildbuddy \
            --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }} \
            --build_event_json_file=build_events.json \
            --nobuild_event_json_file_path_conversion \
            --remote_download_regex='.*/test.xml'
        continue-on-error: true

      - name: Process test results
        if: ${{ always() }}
        uses: trunk-io/analytics-uploader@main
        env:
          TRUNK_PUBLIC_API_ADDRESS: ${{ vars.TRUNK_API_ENDPOINT }}
        with:
          bazel-bep-path: build_events.json
          org-slug: ${{ vars.ORG_SLUG }}
          token: ${{ secrets.TRUNK_TOKEN }}
          previous-step-outcome: ${{ steps.run_tests.outcome }}
