name: PHP Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request: {}

jobs:
  php_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1      - uses: actions/checkout@v4

      - name: Install lib sodium
        run: |
          sudo apt update
          sudo apt install -y libsodium-dev libsodium23

      - name: Setup PHP Action
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # 2.31.1        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: 8.3.10
          tools: php-cs-fixer, phpunit
          ini-values: error_reporting=-1, display_errors=On

      - name: Run phpunit tests
        run:
          phpunit -c php/phpunit/phpunit.xml --bootstrap php/phpunit/src/autoload.php --log-junit
          tests/phpunit_test.xml

      - name: Upload results
        # Run this step even if the test step ahead fails
        if: ${{ always() }}
        uses: trunk-io/analytics-uploader@main
        with:
          # Path to your test results.
          junit-paths: "**/*_test.xml"
          # Provide your Trunk organization slug.
          org-slug: trunk
          # Provide your Trunk API token as a GitHub secret.
          token: ${{ secrets.TRUNK_TOKEN }}
        continue-on-error: true

      - name: Upload JUnit XML artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2        uses: actions/upload-artifact@v4
        with:
          name: php-junit-results
          path: "**/*_test.xml"
          retention-days: 7
