name: PR Workflow

on:
  pull_request: {}

jobs:
  scheduler:
    runs-on: eli
    outputs:
      skip: ${{ steps.dynamic-scheduler.outputs.skip }}
    steps:
      - uses: actions/checkout@v4

      - name: dynamic-scheduler
        id: dynamic-scheduler
        uses: ./.github/actions/dynamic-scheduler
        with:
            debug: true

      - name: Debug Skip Output
        run: |
          echo "Skip output contents:"
          echo "${{ steps.dynamic-scheduler.outputs.skip }}"

  # step0:
  #   needs: scheduler
  #   runs-on: eli
  #   steps:
  #     - name: Debug Skip JSON
  #       run: |
  #         echo "Raw skip output:"
  #         echo "${{ needs.scheduler.outputs.skip }}"
  #         echo "Parsed skip JSON:"
  #         echo "${{ fromJSON(needs.scheduler.outputs.skip) }}"
  #         echo "Individual skip values:"
  #         echo "step1: ${{ fromJSON(needs.scheduler.outputs.skip).step1 }}"
  #         echo "step2: ${{ fromJSON(needs.scheduler.outputs.skip).step2 }}"
  #         echo "step3: ${{ fromJSON(needs.scheduler.outputs.skip).step3 }}"

  step1:
    needs: scheduler
    if: ${{ !fromJSON(needs.scheduler.outputs.skip).step1 }}
    runs-on: eli
    steps:
      - name: Step 1
        run: |
          sleep 10
          exit 0

  step2:
    needs: scheduler
    if: ${{ !fromJSON(needs.scheduler.outputs.skip).step2 }}
    runs-on: eli
    steps:
      - name: Step 2
        run: |
          sleep 20
          exit 0

  step3:
    needs: scheduler
    if: ${{ !fromJSON(needs.scheduler.outputs.skip).step3 }}
    runs-on: eli
    steps:
      - name: Step 3
        run: |
          sleep 10
          exit 0 

  step4:
      needs: scheduler
      if: ${{ !fromJSON(needs.scheduler.outputs.skip).step4 }}
      runs-on: eli
      steps:
        - name: Step 4
          run: |
            sleep 10
            exit 0           