name: PR Workflow

on:
  pull_request: {}

jobs:
      

  scheduler:
    runs-on: eli
    steps:
      - uses: actions/checkout@v4

      - name: dynamic-scheduler
        uses: ./.github/actions/dynamic-scheduler

  step1:
    needs: scheduler
    runs-on: eli
    steps:
      - name: Step 1
        run: |
          sleep 10
          exit 0

  step2:
    needs: scheduler
    runs-on: eli
    steps:
      - name: Step 2
        run: |
          sleep 10
          exit 0

  step3:
    needs: scheduler
    runs-on: eli
    steps:
      - name: Step 3
        run: |
          sleep 10
          exit 0 