name: Trunk Check

on:
  pull_request:

permissions:
  contents: read
  # Required for Trunk to post annotations
  checks: write

jobs:
  trunk_check:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          cache: false
          timeout-seconds: 1500 # 25 minutes in seconds
          cat-trunk-debug-logs: true
